---
title: "An overview of the abaR package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{An overview of the abaR package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = T, comment = "#>")
options(tibble.print_min = 5L, tibble.print_max = 5L)
```

## Head 1

test test

```{r setup}
library(dplyr, warn.conflicts = FALSE)
library(aba)
```

```{r}
data <- adnimerge %>% dplyr::filter(VISCODE == 'bl')

model_spec <- aba_model() %>%
  set_data(data) %>% 
  set_groups(
    everyone(),
    DX_bl %in% c('MCI','AD'),
    labels = c('All','MCI+AD')
  ) %>%
  set_outcomes(ConvertedToAlzheimers, CSF_ABETA_STATUS_bl,
               labels=c('AD','CSF Abeta')) %>%
  set_predictors(
    PLASMA_ABETA_bl,
    PLASMA_PTAU181_bl,
    PLASMA_NFL_bl,
    c(PLASMA_ABETA_bl, PLASMA_PTAU181_bl, PLASMA_NFL_bl)
  ) %>%
  set_stats(stat_glm(std.beta=T))

model_fit <- model_spec %>% fit()
model_summary <- model_fit %>% summary()

```

Here is a table view of the results:
```{r}
model_summary %>% as_reactable()
```

### Sub 1

test test

### Sub 2

test test

## Head 2

test test

## Head 3

test test
